language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r spring-webservice *
  - mkdir -p deploy
  - mv spring-webservice.zip deploy/spring-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: msjump-spring-webservice-deploy # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: skh2000k/spring-webservice
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: msjump-spring-webservice-deploy # S3 버킷
    key: spring-webservice.zip # S3 버킷에 저장된 spring-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: spring-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: spring-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: skh2000k/spring-webservice
      branch: master

notifications:
  email:
    recipients:
      - skh2000k@gmail.com